import type { Metadata } from "next";
import { requirePermission } from "@/lib/auth/guard";
import { hasPermission } from "@/lib/auth/permissions";
import { getComplianceReportExports } from "@/lib/compliance";
import { recordComplianceReportSubmission } from "@/app/admin/compliance/report-actions";
import { GenerateReportForm } from "@/app/admin/compliance/GenerateReportForm";
import { Container } from "@/components/ui/Container";
import { PageHeading } from "@/components/ui/PageHeading";
import { Card } from "@/components/ui/Card";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { DataTable } from "@/components/ui/Table";

export const metadata: Metadata = { title: "Compliance reports" };

/**
 * The circular's explicit compliance-report / live-URL submission requirement
 * (docs/requirements.md §3, docs/compliance-matrix.md §2): generates a durable, timestamped
 * snapshot of every requirement's status for reporting to the Office of the Inspector of
 * Colleges, and records when that report was actually submitted. Generating is not the same
 * as submitting — a college may generate several drafts before the one it actually sends.
 * Both actions require `compliance:verify` (Principal/Administrator/Super Admin); anyone with
 * `compliance:view` can see the list, mirroring the rest of the Compliance module.
 */
export default async function ComplianceReportsPage({
  searchParams,
}: {
  searchParams: Promise<{ reportError?: string }>;
}) {
  const user = await requirePermission("compliance:view");
  const { reportError } = await searchParams;
  const canVerify = hasPermission(user.permissions, "compliance:verify");

  const reports = await getComplianceReportExports();

  return (
    <Container>
      <div className="flex flex-col gap-6 py-10">
        <PageHeading
          title="Compliance reports"
          description="Generate and track the compliance report + live website URL submitted to the Office of the Inspector of Colleges."
        />

        {reportError ? <Alert tone="danger">{reportError}</Alert> : null}

        {canVerify ? (
          <Card>
            <h2 className="mb-3 text-base font-semibold text-foreground">Generate a new report</h2>
            <GenerateReportForm />
          </Card>
        ) : null}

        <DataTable
          caption="Generated compliance reports"
          rows={reports}
          getRowKey={(row) => row.id}
          emptyState={{ title: "No compliance reports generated yet." }}
          columns={[
            {
              key: "generatedAt",
              header: "Generated",
              render: (row) => row.generatedAt.toLocaleString(),
            },
            {
              key: "generatedBy",
              header: "Generated by",
              render: (row) => row.generatedByName,
            },
            {
              key: "status",
              header: "Verified",
              render: (row) => `${row.verifiedCount} / ${row.totalCount}`,
            },
            {
              key: "websiteUrl",
              header: "Website URL",
              render: (row) => (
                <a
                  href={row.websiteUrl}
                  target="_blank"
                  rel="noreferrer noopener"
                  className="text-brand hover:underline"
                >
                  {row.websiteUrl}
                </a>
              ),
            },
            {
              key: "submitted",
              header: "Submitted",
              render: (row) => {
                if (row.submittedAt) {
                  return `${row.submittedAt.toLocaleString()} by ${row.submittedByName ?? "—"}`;
                }
                if (!canVerify) return "Not yet submitted";
                return (
                  <form action={recordComplianceReportSubmission.bind(null, row.id)}>
                    <Button type="submit" variant="secondary">
                      Mark as submitted
                    </Button>
                  </form>
                );
              },
            },
          ]}
        />
      </div>
    </Container>
  );
}
